"""Extract every asset from the original REFLEX (1988, 3F Productions) files.

Outputs
  assets/sprites/NN_name.png   each shape at native 27x17 and 8x (non-square EGA pixels corrected)
  assets/sprite_sheet.png      all 27 shapes, 4x, labelled
  assets/sprites.json          palette-indexed pixel data + names + palette
  assets/strings.txt           all game text found in REFLEX.EXE
  assets/top40.json            the high-score table from REFLEX.T40
  web/js/sprites.js            the sprite data the web game loads

REFLEX.EGA layout: 27 records of 280 bytes. Each record is a Borland BGI
getimage() buffer: u16 width-1, u16 height-1, then per scanline 4 bit-planes
(intensity, red, green, blue order) of 4 bytes each, plus 4 bytes of padding.
The game copies the first 279 bytes of each record into memory, which drops
only that padding.
"""
import base64, json, os, re, struct
from PIL import Image, ImageDraw

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
SRC = os.path.join(ROOT, 'sourcefiles', 'reflex')
OUT = os.path.join(ROOT, 'assets')

NAMES = ['worm_head', 'worm_trail', 'clear_trail', 'empty_space', 'pigman', 'transport',
         'palmtree', 'down_arrow', 'martini', 'extraman', 'demon', 'super_transport',
         'sunny_island', 'cross', 'pre_barren_area', 'barren_area'] + \
        [f'points_{n}' for n in range(100, 1001, 100)] + ['worm_head_powered']

# Default EGA palette. main() calls setpalette(1, RED), so index 1 shows as red.
EGA = [(0, 0, 0), (0, 0, 170), (0, 170, 0), (0, 170, 170), (170, 0, 0), (170, 0, 170),
       (170, 85, 0), (170, 170, 170), (85, 85, 85), (85, 85, 255), (85, 255, 85),
       (85, 255, 255), (255, 85, 85), (255, 85, 255), (255, 255, 85), (255, 255, 255)]
GAME_PALETTE = list(EGA)
GAME_PALETTE[1] = EGA[4]

W, H, REC = 27, 17, 280
ROW_BYTES = 4  # ceil(27 / 8)
PLANE_BITS = [3, 2, 1, 0]  # plane order within a scanline -> palette bit


def decode_shapes(raw):
    shapes = []
    for k in range(len(raw) // REC):
        base = k * REC
        w1, h1 = struct.unpack_from('<HH', raw, base)
        assert (w1 + 1, h1 + 1) == (W, H), (k, w1, h1)
        px = []
        for y in range(H):
            row = base + 4 + y * ROW_BYTES * 4
            for x in range(W):
                v = 0
                for p, bit in enumerate(PLANE_BITS):
                    if raw[row + p * ROW_BYTES + x // 8] >> (7 - x % 8) & 1:
                        v |= 1 << bit
                px.append(v)
        shapes.append(px)
    return shapes


def to_image(px, pal=GAME_PALETTE):
    img = Image.new('RGB', (W, H))
    img.putdata([pal[v] for v in px])
    return img


def main():
    os.makedirs(os.path.join(OUT, 'sprites'), exist_ok=True)
    raw = open(os.path.join(SRC, 'REFLEX.EGA'), 'rb').read()
    shapes = decode_shapes(raw)
    assert len(shapes) == len(NAMES)

    # EGA 640x350 was shown on a 4:3 monitor, so pixels are ~1.37x taller than wide.
    for i, (name, px) in enumerate(zip(NAMES, shapes)):
        img = to_image(px)
        img.save(os.path.join(OUT, 'sprites', f'{i:02d}_{name}.png'))
        img.resize((W * 8, round(H * 8 * 1.37)), Image.NEAREST).save(
            os.path.join(OUT, 'sprites', f'{i:02d}_{name}@8x.png'))

    cols, s = 7, 4
    cw, chh = W * s + 16, round(H * s * 1.37) + 30
    sheet = Image.new('RGB', (cols * cw + 16, ((len(shapes) + cols - 1) // cols) * chh + 16), (24, 26, 36))
    dr = ImageDraw.Draw(sheet)
    for i, px in enumerate(shapes):
        x, y = 16 + (i % cols) * cw, 16 + (i // cols) * chh
        sheet.paste(to_image(px).resize((W * s, round(H * s * 1.37)), Image.NEAREST), (x, y))
        dr.text((x, y + round(H * s * 1.37) + 2), f'{i} {NAMES[i]}', fill=(220, 220, 230))
    sheet.save(os.path.join(OUT, 'sprite_sheet.png'))

    packed = bytes(v for px in shapes for v in px)
    meta = {'width': W, 'height': H, 'pixelAspect': 1.37, 'names': NAMES,
            'palette': ['#%02x%02x%02x' % c for c in GAME_PALETTE],
            'data': base64.b64encode(packed).decode()}
    json.dump({**meta, 'pixels': shapes}, open(os.path.join(OUT, 'sprites.json'), 'w'))
    with open(os.path.join(ROOT, 'web', 'js', 'sprites.js'), 'w') as f:
        f.write('// Generated by tools/extract_assets.py from REFLEX.EGA. Do not edit.\n')
        f.write('// 27 palette-indexed 27x17 shapes, one byte per pixel, base64.\n')
        f.write('window.REFLEX_SPRITES = ' + json.dumps(meta) + ';\n')

    exe = open(os.path.join(SRC, 'REFLEX.EXE'), 'rb').read()
    data_seg = exe[0x400 + 0xd6e0:]  # DGROUP (segment 0x0d6e)
    strings = [m.group().decode().rstrip() for m in re.finditer(rb'[\x20-\x7e]{6,}', data_seg)]
    open(os.path.join(OUT, 'strings.txt'), 'w').write('\n'.join(s for s in strings if s.strip()) + '\n')

    t40 = open(os.path.join(SRC, 'REFLEX.T40'), 'rb').read()
    table = [{'name': t40[i:i + 20].decode().strip(), 'level': int(t40[i + 20:i + 23]),
              'score': int(t40[i + 23:i + 30])} for i in range(0, len(t40), 30)]
    json.dump(table, open(os.path.join(OUT, 'top40.json'), 'w'), indent=1)
    print(f'{len(shapes)} sprites, {len(strings)} strings, {len(table)} score rows')


if __name__ == '__main__':
    main()
